"""initial schema

Revision ID: 055b45074884
Revises: 
Create Date: 2026-02-13 17:21:47.648743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055b45074884'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('idclient', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=True),
    sa.Column('reference_externe', sa.String(length=80), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idclient'),
    sa.UniqueConstraint('reference_externe')
    )
    op.create_table('commercants',
    sa.Column('idcommercant', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('categorie', sa.String(length=80), nullable=True),
    sa.Column('pays', sa.String(length=80), nullable=True),
    sa.Column('ville', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('idcommercant')
    )
    op.create_table('roles',
    sa.Column('idr', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idr'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('cartes',
    sa.Column('idcarte', sa.UUID(), nullable=False),
    sa.Column('pan_masque', sa.String(length=30), nullable=False),
    sa.Column('emetteur', sa.String(length=50), nullable=True),
    sa.Column('mois_expiration', sa.Integer(), nullable=True),
    sa.Column('annee_expiration', sa.Integer(), nullable=True),
    sa.Column('idclient', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idclient'], ['clients.idclient'], ),
    sa.PrimaryKeyConstraint('idcarte')
    )
    op.create_table('utilisateurs',
    sa.Column('iduser', sa.UUID(), nullable=False),
    sa.Column('nom_complet', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idr', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idr'], ['roles.idr'], ),
    sa.PrimaryKeyConstraint('iduser'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transactions',
    sa.Column('idtransac', sa.UUID(), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('idclient', sa.UUID(), nullable=False),
    sa.Column('idcarte', sa.UUID(), nullable=False),
    sa.Column('idcommercant', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idcarte'], ['cartes.idcarte'], ),
    sa.ForeignKeyConstraint(['idclient'], ['clients.idclient'], ),
    sa.ForeignKeyConstraint(['idcommercant'], ['commercants.idcommercant'], ),
    sa.PrimaryKeyConstraint('idtransac')
    )
    op.create_table('predictions_modele',
    sa.Column('idmod', sa.UUID(), nullable=False),
    sa.Column('nom_modele', sa.String(length=50), nullable=False),
    sa.Column('version_modele', sa.String(length=50), nullable=True),
    sa.Column('score_risque', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('est_anomalie', sa.Boolean(), nullable=False),
    sa.Column('seuil', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idtransac', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idtransac'], ['transactions.idtransac'], ),
    sa.PrimaryKeyConstraint('idmod')
    )
    op.create_table('alertes',
    sa.Column('idalerte', sa.UUID(), nullable=False),
    sa.Column('criticite', sa.String(length=10), nullable=False),
    sa.Column('statut', sa.String(length=15), nullable=False),
    sa.Column('raison', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_cloture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idtransac', sa.UUID(), nullable=False),
    sa.Column('idmod', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['idmod'], ['predictions_modele.idmod'], ),
    sa.ForeignKeyConstraint(['idtransac'], ['transactions.idtransac'], ),
    sa.PrimaryKeyConstraint('idalerte'),
    sa.UniqueConstraint('idtransac')
    )
    op.create_table('validations',
    sa.Column('idval', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=15), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idalerte', sa.UUID(), nullable=False),
    sa.Column('iduser', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idalerte'], ['alertes.idalerte'], ),
    sa.ForeignKeyConstraint(['iduser'], ['utilisateurs.iduser'], ),
    sa.PrimaryKeyConstraint('idval')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations')
    op.drop_table('alertes')
    op.drop_table('predictions_modele')
    op.drop_table('transactions')
    op.drop_table('utilisateurs')
    op.drop_table('cartes')
    op.drop_table('roles')
    op.drop_table('commercants')
    op.drop_table('clients')
    # ### end Alembic commands ###
