"""add kyc fields to clients

Revision ID: 1dd8e9bea22f
Revises: 055b45074884
Create Date: 2026-02-15 13:36:29.586623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd8e9bea22f'
down_revision: Union[str, Sequence[str], None] = '055b45074884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('pays_residence', sa.String(length=80), nullable=True))
    op.add_column('clients', sa.Column('profession', sa.String(length=80), nullable=True))
    op.add_column('clients', sa.Column('revenu_mensuel_estime', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('clients', sa.Column('plafond_carte_journalier', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'plafond_carte_journalier')
    op.drop_column('clients', 'revenu_mensuel_estime')
    op.drop_column('clients', 'profession')
    op.drop_column('clients', 'pays_residence')
    # ### end Alembic commands ###
