"""add kyc fields to clients

Revision ID: 579cdb0085bf
Revises: 1dd8e9bea22f
Create Date: 2026-02-15 13:46:05.597746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579cdb0085bf'
down_revision: Union[str, Sequence[str], None] = '1dd8e9bea22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
